trainer:
  precision: 16-mixed
  accelerator: "gpu"
  max_epochs: 1200
  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      project: "master_thesis"
      save_dir: /home/jakub/Developer/Magisterka/ai-lightning/logs/model_scores
      name: "raunet_2D"
      log_model: "all"
  check_val_every_n_epoch: 2
  devices: [0]
  log_every_n_steps: 1
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: "val_loss"
        mode: "min"
        save_weights_only: True
        dirpath: "/home/jakub/Developer/Magisterka/ai-lightning/logs/model_scores"
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: 'epoch'
    - class_path: agatston.callbacks.CustomCallback.LogPredictionsCallback
model:
  class_path: agatston.models.RaUNet2D.RaUNet2D
  init_args:
    optimizer:
      class_path: torch.optim.AdamW
      init_args:
        lr: 1e-4
data:
  class_path: agatston.data.calcium_dataset.CalciumScoreDataModule
  init_args:
    cascore_path_yaml: "/home/jakub/Developer/Magisterka/data/default/configs/processed_paths_setup_0.yaml"
    batch_size: 10
    cache_rate: 1.0
    num_workers: 15
    transforms_train:
      class_path: agatston.transforms.standardTransforms.Transformations2D
    transforms_val:
      class_path: agatston.transforms.standardTransforms.TransformationsVal

