fit:
  trainer:
    precision: 16-mixed
    accelerator: "auto"
    max_epochs: 2600
    logger:
      class_path: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
      init_args:
        save_dir: /home/jakub/Developer/Magisterka/ai-lightning/logs/model_scores
        name: lightning_logs
        prefix: raunet
    check_val_every_n_epoch: 50
    devices: [0]
    log_every_n_steps: 1
    callbacks:
      - class_path: lightning.pytorch.callbacks.ModelCheckpoint
        init_args:
          monitor: "val_loss"
          mode: "min"
          save_weights_only: True
          dirpath: "/home/jakub/Developer/Magisterka/ai-lightning/logs/model_scores"
      - class_path: lightning.pytorch.callbacks.EarlyStopping
        init_args:
          monitor: "val_loss"
          patience: 15
      - class_path: lightning.pytorch.callbacks.LearningRateMonitor
        init_args:
          logging_interval: 'epoch'
  model:
    class_path: agatston.models.RaUNet3D.RaUNet
    init_args:
      optimizer:
        class_path: torch.optim.AdamW
        init_args:
          lr: 1e-4
  data:
    class_path: agatston.data.calciumDataset3D.CalciumScore3DDataModule
    init_args:
      cascore_path_yaml: "/home/jakub/Developer/Magisterka/data/default/configs/processed_paths_setup_0.yaml"
      batch_size: 4
      cache_rate: 1.0
      num_workers: 12
