trainer:
  precision: 16-mixed
  accelerator: "gpu"
  max_epochs: 1600
  logger:
    - class_path: lightning.pytorch.loggers.wandb.WandbLogger
      init_args:
        project: "master_thesis"
        save_dir: /home/jacob/Developer/Hemolens/plaques/others/ai-lightning/logs/model_scores
        name: "unetr_2D"
        log_model: "all"
  check_val_every_n_epoch: 50
  devices: [0]
  log_every_n_steps: 1
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: "val_loss"
        mode: "min"
        save_weights_only: True
        dirpath: "/home/jacob/Developer/Hemolens/plaques/others/ai-lightning/logs/model_scores"
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: 'epoch'
    - class_path: agatston.callbacks.CustomCallback.LogPredictionsCallback
model:
  class_path: agatston.models.UNETR2D.UNETR2D
  init_args:
    optimizer:
      class_path: torch.optim.AdamW
      init_args:
        lr: 1e-4
data:
  class_path: agatston.data.calcium_dataset.CalciumScoreDataModule
  init_args:
    cascore_path_yaml: "/home/jacob/Developer/Hemolens/plaques/calcium_scoring_cardiac_ct/./dataCaScore/default/configs/processed_paths_setup_0.yaml"
    batch_size: 6
    cache_rate: 1.0
    num_workers: 15
    transforms_train:
      class_path: agatston.transforms.standard_transforms.Transformations2D
    transforms_val:
      class_path: agatston.transforms.standard_transforms.TransformationsVal
